for_sale/for_sale/urls.py
#import document as document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('for_sale_app.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

for_sale/for_sale_app/urls.py
from .import views
from django.urls import path
app_name = 'for_sale_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:my_id>/', views.product_detail, name='product-detail'),
    path('create', views.product_create_view, name='product-create')
]

for_sale/for_sale_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Product(models.Model):
    PRODUCT_CATEGORIES = [
        ('HB', 'Health and beauty'),
        ('OTHER', 'Other'),
        ('ELEC', 'Electronics'),
        ('HOME', 'Home'),
        ('SPORT', 'Sports and exercise'),
        ('ENTER', 'Entertainment'),
        ('FOOD', 'Food'),
        ('BOOK', 'Books'),
    ]

    # left is stored in database, right is what's displayed

    category = models.CharField(max_length=5, choices=PRODUCT_CATEGORIES, default='OTHER')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    price = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    picture = models.ImageField(default='images/default.jpg', null=True, upload_to='images/', blank=True, )
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("for_sale_app:product-detail", kwargs={"my_id": self.id})

for_sale/for_sale_app/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price',
            'category',
            'picture'
        ]

for_sale/for_sale_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from .forms import ProductForm
# Create your views here.


def index(request):
    queryset = Product.objects.all()
    context = {
        'product_list': queryset
    }
    return render(request, 'for_sale_app/index.html', context)


def product_detail(request, my_id):
    obj = get_object_or_404(Product, id=my_id)
    context = {
        "object": obj
    }
    return render(request, 'for_sale_app/product_detail.html', context)


def product_create_view(request):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = ProductForm()
    context = {
        'form': form
    }
    return render(request, "for_sale_app/product_create.html", context)

for_sale/for_sale_app/templates/for_sale_app/product_create.html
{% extends 'for_sale_app/base.html' %}
{% load static %}
{% block content %}
    <form action="" method="POST"> {% csrf_token %}
    {{ form.as_p }} 
    <input type='submit' value='Save' />
    </form>
{% endblock %}

for_sale/templates/for_sale_app/base.html
<!doctype html>
<html>
{% load static %}
<head>
    <title>For Sale App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'for_sale_app/style.css' %}">
</head>
<body>
<nav>
    <ul class="w-50 d-flex justify-content-between">
        <li><a href={% url 'for_sale_app:index' %}>Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
</nav>
{% block content %}

{% endblock %}
</body>
</html>

for_sale/templates/for_sale_app/index.html
{% extends 'for_sale_app/base.html' %}
{% load static %}
{% block content %}

    <h1>Index/Home page</h1>

    <ul>
    {% for product in product_list %}
        <li><a href="{{ product.get_absolute_url }}">{{ product }}</a></li>
    {% endfor %}
    </ul>

{% endblock %}

for_sale/templates/for_sale_app/product_create.html
{% extends 'for_sale_app/base.html' %}
{% load static %}
{% block content %}
    <h1>Add new item for sale</h1>
    <form action="" method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save' />
    </form>
{% endblock %}

for_sale/templates/for_sale_app/product_detail.html
{% extends 'for_sale_app/base.html' %}
{% load static %}
{% block content %}

<h1>Product detail</h1>
    <p>{{ object }}</p>
    <p>£{{ object.price }}</p>
    <p>Seller: {{ object.user }}</p>
    <p>Category: {{ object.get_category_display }}</p>
    <p>Description: {{ object.description }}</p>
    {% if object.picture %}
        <img class="product-detail-picture" src="{% static object.picture %}">
    {% else %}
        <img class="product-detail-picture" src="{% static 'images/default.jpg' %}"
    {% endif %}
{% endblock %}